name: Deploying Infrastructure to AWS

on:
  push:
    branches:
      - main
env:
  AWS_REGION: eu-west-2

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        user:
          - Esther
          - Charles
          - Osi
          - Taiwo
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets["AWS_ACCESS_KEY_ID_" + matrix.user] }}
          aws-secret-access-key: ${{ secrets["AWS_SECRET_ACCESS_KEY_" + matrix.user] }}
          aws-region: ${{ env.AWS_REGION }}
 
