name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
   

  #build:

    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: terraform-infra # name of Docker Hub ID
      IMAGE_NAME: tictactoe
      IMAGE_TAG: ${{ github.run_number }} # $GITHUB_RUN_NUMBER
 
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --tag $IMAGE_NAME:$IMAGE_TAG

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        format: 'sarif'
        #report: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Image to Docker Hub
      run:
        docker push $IMAGE_NAME:$IMAGE_TAG
