name: Python Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  AWS_REGION: eu-west-2

permissions:
  id-token: write
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
      - name: Run Tests
        run: |
          python -m unittest discover
      - name: Run Linter
        run: |
          pylint --fail-under=8 tictactoe.py
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      #- name: Testing tfsec
      #  uses: aquasecurity/tfsec-action@v1.0.3
      # with:
      #   path: ./terraform-infra
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::445646923222:role/github-actions-role
          role-session-name: samplerolesession
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.5
          working-directory: ./terraform-infra/
          command: apply

      - name: Initialize Terraform backend
        run: terraform init -input=false -backend-config="bucket=serves-terraform" -backend-config="key=terraform.tfstate"


      - name: Terraform Plan 
        run: terraform plan -input=false

      - name: terraform Apply
        run: terraform apply -auto-approve -input=false

      # - name: Setup Infracost
      #   uses: infracost/actions/setup@v2
      #   # See https://github.com/infracost/actions/tree/master/setup for other inputs
      #   # If you can't use this action, see Docker images in https://infracost.io/cicd
      #   with:
      #     api-key: ${{ secrets.INFRACOST_API_KEY }}

      # # Checkout the base branch of the pull request (e.g. main/master).
      # - name: Checkout base branch
      #   uses: actions/checkout@v3
      #   with:
      #     ref: '${{ github.event.pull_request.base.ref }}'

      #   # Checkout the current PR branch so we can create a diff.
      # - name: Checkout PR branch
      #   uses: actions/checkout@v3

      # # Generate an Infracost diff and save it to a JSON file.
      # - name: Generate Infracost diff
      #   run: |
      #     infracost diff --path=./terraform-infra \
      #                         --format=json \
      #                         --compare-to=/tmp/infracost-base.json \
      #                         --out-file=/tmp/infracost.json

     # https://github.com/infracost/actions/tree/master/examples/terraform-project
          
     # - name: terraform Destroy
      #  run: terraform destroy -auto-approve
       