name: Python Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  AWS_REGION: eu-west-2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint

      - name: Run Tests
        run: |
          python -m unittest discover

      - name: Run Linter
        run: |
          pylint --fail-under=8 tictactoe.py

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        user:
          - Esther
          - Charles
          - Osi
          - Taiwo
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets['AWS_ACCESS_KEY_ID_'+$matrix.user] }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets['AWS_SECRET_ACCESS_KEY_'+$matrix.user] }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to AWS
        run: |
          # Replace this with your actual deployment command
          echo "Deploying with user ${matrix.user}"
