name: Python Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  AWS_REGION: eu-west-2

permissions:
  id-token: write
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3



      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
      - name: Run Tests
        run: |
          python -m unittest discover
      - name: Run Linter
        run: |
          pylint --fail-under=8 tictactoe.py
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

    # - name: Testing tfsec
      #   uses: aquasecurity/tfsec-action@v1.0.3
      #   with:
      #     path: ./terraform-infra

      - name: Terrascan
        uses: accurics/setup-terrascan@v1
        run: |
          terrascan scan -f ./terraform-infra
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::445646923222:role/github-actions-role
          role-session-name: samplerolesession
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.9
          working-directory: ./terraform-infra/
          command: apply

      - name: Initialize Terraform backend
        run: terraform init -input=false -backend-config="bucket=serves-terraform" -backend-config="key=terraform.tfstate"


      - name: Terraform Plan 
        run: terraform plan -input=false

      - name: terraform Apply
        run: terraform apply -auto-approve -input=false

      - name: Costs calculations
        run: infracost 

      - name: terraform Destroy
        run: terraform destroy -auto-approve
       